### ISSUE TITLE
期待微调脚本

### ISSUE THREAD

**Issue by caizhuoyue77** [thu-coai/CharacterGLM-6B#17]
### Feature request  / 功能建议

期待微调脚本！想用来模拟一些虚拟角色说话～想收集数据来进行微调，非常期待！

### Motivation / 动机

想用数据微调CharacterGLM模拟虚拟人物！

### Your contribution / 您的贡献

没有

**Comment by zRzRzRzRzRzRzR** [comment]
目前暂时不会推出微调脚本，之后可能根据新的工作一起推出，现在可以尝试直接使用GLM2的微调脚本尝试。

**Comment by caizhuoyue77** [comment]
> 目前暂时不会推出微调脚本，之后可能根据新的工作一起推出，现在可以尝试直接使用GLM2的微调脚本尝试。

哦哦，GLM2的就可以微调CharacterGLM了是吗？
