### ISSUE TITLE
[question] 据我所知apache-2.0协议是允许有条件限制地商用的，但是readme中提到不可商用？

### ISSUE THREAD

**Issue by VampireAchao** [thu-coai/CharacterGLM-6B#18]
### System Info / 系統信息

非常欢迎各种声音讨论

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

.

### Expected behavior / 期待表现

.

**Comment by zRzRzRzRzRzRzR** [comment]
阿帕奇协议的是这个代码
