### ISSUE TITLE
期待profile数据

### ISSUE THREAD

**Issue by smartliuhw** [thu-coai/CharacterGLM-6B#19]
### Feature request  / 功能建议

论文中提到会公开的profile数据，希望获得并学习

### Motivation / 动机

为了学术研究

### Your contribution / 您的贡献

暂无

**Comment by jfzhouyoo** [comment]
将于近期开源，欢迎follow～

**Comment by cizhenshi** [comment]
> 将于近期开源，欢迎follow～

数据开源了吗？貌似没有搜索到

**Comment by jfzhouyoo** [comment]
已经开源在本仓库

**Comment by jfzhouyoo** [comment]
> > 将于近期开源，欢迎follow～
> 
> 数据开源了吗？貌似没有搜索到

已经开源在本仓库
