### ISSUE TITLE
user_info和bot_info的提示优先级

### ISSUE THREAD

**Issue by MING-ZCH** [thu-coai/CharacterGLM-6B#2]
# user_info和bot_info的提示优先级
1. 想询问info内容是以system prompt设定的吗？模型能否学习到info中的知识
2. 智谱的characterGLM接口，temperature设定是多少？
谢谢

**Comment by jfzhouyoo** [comment]
Sorry for the delay!

Response#1:
bot_info和user_info是设定的bot和user扮演的角色人设，并不等于智能助手场景的instruction或prompt；
CharacterGLM的推理服务有预设prompt，实现时会将bot_info和user_info拼接到prompt中。

Response#2:
temperature = 0.9

**Comment by MING-ZCH** [comment]
Thanks！
Wish your team makes better！
