### ISSUE TITLE
有计划公布部分数据集嘛？

### ISSUE THREAD

**Issue by yin214** [thu-coai/CharacterGLM-6B#28]
### Feature request  / 功能建议

/

### Motivation / 动机

/

### Your contribution / 您的贡献

/

**Comment by jfzhouyoo** [comment]
将于近期开源，欢迎follow～

**Comment by xiaojingli** [comment]
> 将于近期开源，欢迎follow～

请问开源有后续了吗~

**Comment by jfzhouyoo** [comment]
你好，数据已开源
