### ISSUE TITLE
数据集的语言形式（中英文）

### ISSUE THREAD

**Issue by Zc0812** [thu-coai/CharacterGLM-6B#29]
### Feature request  / 功能建议

请教一下
1. 250个角色里面中国角色和外国角色都有吗？
2. 角色扮演的数据集，采用语言是中英文都有吗？

### Motivation / 动机

无

### Your contribution / 您的贡献

无

**Comment by jfzhouyoo** [comment]
1. 250个角色中包含中外角色
2. 将开源中英双语的数据集

**Comment by jfzhouyoo** [comment]
你好，数据已开源
